### ISSUE TITLE
Local simulations

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/psidm-halo-reconstruction#10]
### Setup
- [ ] Reconstruct the local wave function in the central region of a halo
- [ ] Periodic BC for wave function
- [ ] Isolated gravity
- [ ] [Optional] Regard the outer halo (i.e., materials outside the simulation region) as an external potential
  - [ ] Confirm the total potential profile
  - [ ] May not be necessary actually since (i) central region doesn't feel the gravity from the outside and (ii) central region will still be confined thanks to the periodic BC

### Tasks
- [ ] First, verify that the overall structure (e.g., density profile) remains stable
- [ ] Investigate if the local simulations can get consistent results with the global simulations
  - [ ] Soliton oscillations
  - [ ] Soliton random walk

### Notes
- This is important since local simulations are much faster, especially for massive halos, and thus can be very useful for investigating the impact of a central soliton on its surrounding environment.
- Related projects
  - CMZ
  - Bar slow-down
  - Core-halo relation
  - SMBH
  - Disc heating
