### ISSUE TITLE
Core-halo relation

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/psidm-halo-reconstruction#11]
### Setup
- [ ] Remove the soliton from the reconstructed halo
- [ ] Add a small inflow velocity in the inner region (say within a few kpc).
  - [ ] Make sure that the enclosed mass in this region is much larger than the soliton mass
- [ ] Relax the system
- [ ] Test a small halo (say 1e10 Msun) first

### Tasks
- [ ] Will a central density clump reform?
  - [ ] What's the timescale? 
- [ ] How does the reforming central density clump (if any) compare with the following?
  - [ ] soliton solution
  - [ ] core-halo relation
