### ISSUE TITLE
Taiwania 3

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/psidm-halo-reconstruction#7]
### Tasks
- [ ] Test halo reconstruction on GPU nodes
- [ ] Test GAMER
  - [x] Hybrid OpenMP/MPI 
  - [x] CPU nodes
  - [ ] GPU nodes
- [ ] PR of job script
