### ISSUE TITLE
ASGC

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/psidm-halo-reconstruction#8]
### Tasks
- [ ] Test halo reconstruction on GPU nodes
- [ ] Test GAMER
  - [ ] Hybrid OpenMP/MPI 
  - [ ] CPU nodes
  - [ ] GPU nodes
- [ ] PR of job script
