### ISSUE TITLE
Halo analysis

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/psidm-halo-reconstruction#9]
### Tasks (on all three halos)
- [ ] Volume density
  - [ ] Volume rendering
    - [ ] Entire halo
    - [ ] Zoom-in
  - [ ] Slice plot
    - [ ] Entire halo
    - [ ] Zoom-in
  - [ ] Granule size and density variation vs. radius
    - [ ] Compare with the pseudo particle estimation in [Dutta Chowdhury et al. 2021](https://arxiv.org/abs/2105.05268)
    - [ ] [Optional] Compare with [Chan et al. 2020](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.125.111102)
  - [ ] Density profile and rotation curve
- [ ] Surface density
  - [ ] Slice plot
    - [ ] Entire halo
    - [ ] Zoom-in
  - [ ] Granule size and density variation vs. radius
    - [ ] Compare with [Chan et al. 2020](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.125.111102)
    - [ ] Obtain an analytical fitting formula

### Notes
- These analyses can be done in post-processing
